name: Generate Datas

on:
  schedule: # execute every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: generate cobrita_maluca.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/cobrita_maluca.svg?palette=github-dark&color_snake=orange&color_dots=#4c0000,#7f0000,#990000,#b20000,#e50000

          
          
      - name: push cobrita_maluca.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
